### ISSUE TITLE
Sidebar shows two posts instead of one, and is therefore not readable

### ISSUE THREAD

**Issue by jslvtr** [gergelyorosz/GhostSocialCasper#1]
Hello!

I attach an image of the issue.

![screen shot 2015-12-08 at 20 34 19](https://cloud.githubusercontent.com/assets/3788301/11667698/25833cc8-9deb-11e5-9524-0928c3f5d304.png)

**Comment by gergelyorosz** [comment]
Thanks for reporting this @jslvtr . I've addressed the issue and created a new release, it's fixed in [this one](https://github.com/gergelyorosz/GhostSocialCasper/releases/tag/1.1)

You can see how the page looks on my [updated blog](http://blog.pragmaticengineer.com/extending-the-ghost-default-theme-with-social-sidebars/) - the "read this next" and "you might enjoy" links are now in the bottom again, as they orignally were in the Casper theme.
